config/routes.rb
Rails.application.routes.draw do
  #metodo de rotas. cria automaticamente o crud (rotas)
  resources :recipes
  resources :ingredients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  skip_before_action :verify_authenticity_token
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  #método que define o endpoint
  def index
    #o @ é para criar variaveis de instancia (mandar para view)
    @ingredients = Ingredient.all #.all é um metodo para criar um vetor com os dados armazenados na base de dados relacionados
    render json: @ingredients #cria um Json com o vetor acima
  end

  def new
    @ingredients = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      render json: @ingredient
    else
      render json: @ingredient.errors.messages
    end
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name, :amount)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  #método que define o endpoint
  def index
    #o @ é para criar variaveis de instancia (mandar para view)
    @recipes = Recipe.all #.all é um metodo para criar um vetor com os dados armazenados na base de dados relacionados
    render json: @recipes #cria um Json com o vetor acima
  end

  def new
    @recipes = Recipe.new
  end

  def create
    @recipes = Recipe.new(recipes_params)

    if @recipes.save
      redirect_to @recipes, notice: 'Recipe created!'
    else
      render 'new'
    end
  end

  def show
    @recipes = Recipe.find(params[:id])

    @product
  end

  def edit
    @recipes = Recipe.find(params[:id])

    @recipes
  end

  def update
    @recipes = Recipe.find(params[:id])

    if @recipes.update(recipes_params)
      redirect_to @recipes, notice: 'Recipe changed'
    else
      render 'edit'
    end
  end

  def destroy
    @recipes = Recipe.find(params[:id])

    if @recipes.destroy
      redirect_to recipes_path, notice: 'Recipe deleted'
    else
      redirect_to recipes_path, alert: 'Ops, something went wrong'
    end
  end

  private

  def recipes_params
    params.require(:recipes).permit(:id, :name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Simple                     CRM</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to "Products", products_path %>
            </li>
            <li>
              <%= link_to "Companies", companies_path %>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipes do |f| %>

  <% if @recipes.errors.any? %>
    <ul>
      <% @recipes.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.input :name %>
  <%= f.input :description %>

  <%= f.button :submit %>
<% end %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<table class="table">
  <% @recipes.each do |recipe| %>
    <tr>
      <td><%= link_to recipes.name, recipes %></td>
      <td><%= link_to "Edit", edit_recipes_path(product) %></td>
      <td><%= link_to "Delete", recipes, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to "Criar produto", new_recipes_path  %>
</p>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>